export const SHOW_LOADER = "APP/SHOW_LOADER"
export const HIDE_LOADER = "APP/HIDE_LOADER"

export const SWITCH_SEARCH_TYPE = 'SEARCH/SWITCH_SEARCH_TYPE'


export const SEARCH_BY_ADDRESS = "SEARCH/SEARCH_BY_ADDRESS"

export const FETCH_REGION = "SEARCH/SEARCH_BY_ADDRESS/FETCH_REGION"
export const SET_REGION = "SEARCH/SEARCH_BY_ADDRESS/SET_REGION"

export const FETCH_AREA = "SEARCH/SEARCH_BY_ADDRESS/FETCH_AREA"
export const SET_AREA = "SEARCH/SEARCH_BY_ADDRESS/SET_AREA"

export const FETCH_SETTLEMENT = "SEARCH/SEARCH_BY_ADDRESS/FETCH_REGION"
export const SET_SETTLEMENT = "SEARCH/SEARCH_BY_ADDRESS/SET_SETTLEMENT"

export const SET_ADDRESS = "SEARCH/SEARCH_BY_ADDRESS/SET_ADDRESS"



export const SEARCH_BY_NAME = "SEARCH/SEARCH_BY_NAME"
export const SEARCH_BY_NOTARY = "SEARCH/SEARCH_BY_NOTARY"
export const SEARCH_USERS = "SEARCH/SEARCH_USERS"

export const CHANGE_NOTARY_TYPE = "SEARCH/CHANGE_NOTARY_TYPE"

export const SEARCH_PRIVATE_NOTATY = "SEARCH/SEARCH_PRIVATE_NOTATY"
export const SEARCH_STATE_NOTARY_DEPARTMENT = "SEARCH/SEARCH_STATE_NOTARY_DEPARTMENT"

export const CHANGE_USER_SEARCH_TYPE = "SEARCH/CHANGE_USER_SEARCH_TYPE"

export const SEARCH_ADMINISTRATOR = "SEARCH/SEARCH_ADMINISTRATOR"
export const SEARCH_REGISTRATOR = "SEARCH/SEARCH_ADMINISTRATOR"

export const UPDATE_SEARCH_DATA = "SEARCH/UPDATE_SEARCH_DATA"
export const FETCH_SEARCH_DATA = "SEARCH/FETCH_SEARCH_DATA"


export const CHANGE_USER_TYPE = "APP/CHANGE_USER_TYPE"

export const ADMINISTRATOR = "APP/ADMINISTRATOR"
export const REGISTRATOR = "APP/REGISTRATOR"
export const COMMON = "APP/COMMON"