export const SWITCH_SEARCH_TYPE = 'APP/SWITCH_SEARCH_TYPE'

export const SEARCH_BY_ADDRESS = "SEARCH_BY_ADDRESS"
export const SEARCH_BY_NAME = "SEARCH_BY_NAME"
export const SEARCH_BY_NOTARY = "SEARCH_BY_NOTARY"
